src/Me.Mlists.Web/Areas/Painel/Controllers/ParticipanteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Me.Mlists.Models;
using Me.Mlists.Service.Repositories;
using Me.Mlists.Web.Areas.Painel.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Me.Mlists.Web.Areas.Painel.Controllers
{
    [Authorize]
    [Area("Painel")]
    [Route("p/participante")]
    public class ParticipanteController : Controller
    {
        private readonly IParticipanteRepository _participanteRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public ParticipanteController(IParticipanteRepository participanteRepository,
            UserManager<ApplicationUser> userManager)
        {
            _participanteRepository = participanteRepository;
            _userManager = userManager;
        }

        [HttpGet("lista/{listaId}")]
        public async Task<IActionResult> ParticipantesListaAsync(string listaId)
        {
            var participantes = await _participanteRepository.GetParticipanteAllByIdAndListaId(listaId, _userManager.GetUserId(User));
            
            foreach(var item in participantes)
            {
                item.User = await _userManager.FindByIdAsync(item.UserId);
            }

            var modelo = new ParticipanteFormViewModel();
            modelo.participantes = participantes;

            return PartialView("partial/_ParticipantesLista", modelo);
        }

        [ValidateAntiForgeryToken]
        [HttpPost("update-participante")]
        public async Task<IActionResult> UpdateParticipanteAsync([FromBody] ParticipanteFormViewModel modelo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var participante = modelo.ToParticipanteUpdate();
                    var resultado = await _participanteRepository.UpdatePerfilParticipanteAsync(participante, _userManager.GetUserId(User));

                    return Ok(new { mensagem = "Alteração realizada com sucesso!" });
                }
            }
            catch(Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }
            
            return BadRequest(new { mensagens = ModelState.Values.SelectMany(x => x.Errors.Select(x => x.ErrorMessage)) });
        }
    }
}

src/Me.Mlists.Web/Areas/Painel/Views/Participante/partial/_ParticipantesLista.cshtml
@model ParticipanteFormViewModel

<div class="modal remove-hide fade" id="nova-lista-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-secondary"><i class="fas fa-clipboard-list"></i> Participantes:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if (Model.participantes.Count() > 0)
                {
                    <ul class="list-group list-group-flush">
                        @foreach (var participante in Model.participantes)
                        {
                            <li class="list-group-item d-flex  justify-content-between bd-highlight p-1">
                                <p class="m-0 align-self-center">@participante.User.Nome</p>
                                <form class="align-self-center" asp-area="Painel" asp-controller="Participante" asp-action="UpdateParticipante">
                                    <input type="hidden" name="ParticipanteId" value="@participante.Id"/>
                                    <div class="form-group m-0">
                                        <select class="form-control"
                                                 onchange="participante.alterarParticipante(this)" 
                                                name="ParticipantePerfil" 
                                                asp-for="@participante.ParticipantePerfil" 
                                                asp-items="Html.GetEnumSelectList<ParticipantePerfilEnum>()">
                                        </select>
                                    </div>
                                </form>
                            </li>
                        }
                    </ul>
                }
            </div>
        </div>
    </div>
</div>