src/Me.Mlists.Web/Areas/Login/ViewModels/RegistrarViewModel.cs
using Microsoft.AspNetCore.Authentication;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Me.Mlists.Web.Areas.Login.ViewModels
{
    public class RegistrarViewModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Nome(apelido) obrigatório!")]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Email obrigatório!")]
        [EmailAddress(ErrorMessage = "Preencha com um email valido!")]
        public string Email { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Senha obrigatório!")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Senha { get; set; }

        [DataType(DataType.Password)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Confirmar senha obrigatório!")]
        [Display(Name = "Confirmar senha")]
        [Compare("Senha", ErrorMessage = "A senha está diferente do valor confirmar senha.")]
        public string ConfirmarSenha { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }
    }
}

src/Me.Mlists.Web/Areas/Login/Controllers/RegistroController.cs
using Me.Mlists.Models;
using Me.Mlists.Service.Services;
using Me.Mlists.Web.Areas.Login.ViewModels;
using Me.Mlists.Web.Helpers;
using Me.Mlists.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Me.Mlists.Web.Areas.Login.Controllers
{

    [Area("Login")]
    [Route("l/registro")]
    public class RegistroController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailService _emailService;

        public RegistroController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailService emailService)
        {
            _userManager = userManager;
            _emailService = emailService;
            _signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> RegistrarAsync()
        {
            var modelo = new RegistrarViewModel();
            modelo.ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(RegistrarViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                if (await _userManager.FindByEmailAsync(modelo.Email) != null)
                    return View("../ConfirmeEmail/AguardandoConfirmacao");

                var usuario = new ApplicationUser { Nome = modelo.Nome, UserName = modelo.Email, Email = modelo.Email };
                var resultado = await _userManager.CreateAsync(usuario, modelo.Senha);

                if (resultado.Succeeded)
                {
                    await EnviarEmailDeConfirmacaoAsync(usuario);
                    return View("../ConfirmeEmail/AguardandoConfirmacao");
                }
                else
                {
                    AdicionarErros(resultado);
                }
               
            }

            modelo.ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            return View(modelo);
        }

        [HttpPost("reenviar-confirmacao-email", Name = "form_reenviar_confirmacao_email")]
        public async Task<IActionResult> ReenviarConfirmacaoEmailAsync(string usuarioId = null)
        {
            if (usuarioId == null)
                return View("Error");

            var usuario = await _userManager.FindByIdAsync(usuarioId);
            await EnviarEmailDeConfirmacaoAsync(usuario);

            return View("../ConfirmeEmail/AguardandoConfirmacao");
        }

        private async Task EnviarEmailDeConfirmacaoAsync(ApplicationUser usuario)
        {
            var token = await _userManager.GenerateEmailConfirmationTokenAsync(usuario);
            token = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(token));
            var callbackUrl = Url.RouteUrl("Confirmacao_email",
                new { usuarioId = usuario.Id, token = token },
                Request.Scheme);

            var templateEmail = await this.RenderViewToStringAsync("~/Views/TemplateMail/_EmailComButton.cshtml", 
                new EmailComButtonViewModel(
                    titulo: "Seja bem vindo ao MLists!",
                    linkImagem: "https://img.icons8.com/bubbles/100/000000/meeting.png",
                    descricao: "Estamos felizes por ter você conosco. Para acessar sua conta primeiro você precisa confirmar seu email clicando no botão abaixo.",
                    link: callbackUrl,
                    linkDescricao: "Confirmar email")
                );

            await _emailService.SendEmailAsync(usuario.Email, "Confirmação de email - MLists", templateEmail);

        }

        private void AdicionarErros(IdentityResult resultado)
        {
            foreach (var error in resultado.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

src/Me.Mlists.Web/Areas/Login/Controllers/RegistroExternoController.cs
using Me.Mlists.Models;
using Me.Mlists.Web.Areas.Login.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Me.Mlists.Web.Areas.Login.Controllers
{
    [Area("Login")]
    [Route("l/registro-externo")]
    public class RegistroExternoController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RegistroExternoController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpPost("chamada")]
        public IActionResult RegistroExterno(string provider)
        {
            var redirectUrl = Url.Action("RegistroExternoCallback");
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        [HttpGet("chamada-resultado")]
        public async Task<IActionResult> RegistroExternoCallbackAsync(string remoteError = null)
        {
            try
            {
                if (remoteError != null)
                    throw new ArgumentException($"Erro de provedor externo: {remoteError}");

                var info = await _signInManager.GetExternalLoginInfoAsync();

                if (info == null)
                    throw new ArgumentException("Erro ao carregar informações de login externo");

                var email = info.Principal.FindFirstValue(ClaimTypes.Email);

                if (await _userManager.FindByEmailAsync(email) != null)
                    throw new ArgumentException("Este email já possui uma conta");

                var usuario = new ApplicationUser { Nome = info.Principal.FindFirstValue(ClaimTypes.Name), UserName = email, Email = email, EmailConfirmed = true };

                var resultado = await _userManager.CreateAsync(usuario);
                if (resultado.Succeeded)
                {
                    resultado = await _userManager.AddLoginAsync(usuario, info);
                    if (resultado.Succeeded)
                    {
                        await _signInManager.SignInAsync(usuario, isPersistent: false, info.LoginProvider);

                        return LocalRedirect(Url.Action("Index", "Lista", new { area = "Painel" }));
                    }
                    else
                    {
                        throw new ArgumentException($"Não foi possível criar uma conta usando {info.ProviderDisplayName}");
                    }
                }
                else
                {
                    foreach (var error in resultado.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }

            var modelo = new RegistrarViewModel();
            modelo.ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            return View("../Registro/Registrar", modelo);
        }
    }
}

src/Me.Mlists.Web/Areas/Login/Views/Registro/Registrar.cshtml
@model RegistrarViewModel
@{
    ViewData["Title"] = "Registrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/jquery-validation-start.js"></script>
}
<div class="container mt-3">
    <section class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-7 col-lg-5">
            <div class="card mt-4 ml-auto mr-auto">
                <div class="card-header bg-white">
                    <h3><i class="fas fa-sign text-secondary"></i> Registre-se</h3>
                    <p>Olá, preencha os campos para criar uma conta!</p>
                </div>
                <div class="card-body">
                    <form asp-area="Login" asp-controller="Registro" asp-action="Registrar" method="post" class="needs-validation">
                        <div asp-validation-summary="ModelOnly" data-valmsg-summary="true" class="alert alert-danger"></div>
                        <div class="form-group">
                            <label asp-for="Nome" class="font-weight-bold"></label>
                            <input asp-for="Nome" class="form-control" required>
                            <span class="invalid-feedback" asp-validation-for="Nome"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="font-weight-bold"></label>
                            <input asp-for="Email" class="form-control" required>
                            <span class="invalid-feedback" asp-validation-for="Email"></span>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label asp-for="Senha" class="font-weight-bold"></label>
                                    <input asp-for="Senha" class="form-control" required>
                                    <span class="invalid-feedback" asp-validation-for="Senha"></span>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label asp-for="ConfirmarSenha" class="font-weight-bold"></label>
                                    <input asp-for="ConfirmarSenha" class="form-control" required>
                                    <span class="invalid-feedback" asp-validation-for="ConfirmarSenha"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-2">
                            <button type="submit" value="Logar " class="btn btn-danger btn-block">
                                Registre-se agora
                            </button>
                        </div>
                    </form>
                    <div class="text-center mb-3">
                        <h5 class="p-0 m-0"><span class="badge badge-light">ou</span></h5>
                    </div>
                    <section>
                        @{
                            if (Model.ExternalLogins != null && Model.ExternalLogins.Count > 0)
                            {
                                <form id="external-account" asp-area="Login" asp-controller="RegistroExterno" asp-action="RegistroExterno" method="post" class="form-horizontal">
                                    <div>
                                        <p>
                                            @foreach (var provider in Model.ExternalLogins)
                                            {
                                                <button type="submit" class="btn btn-block btn-sm btn-@provider.Name" name="provider" value="@provider.Name" title="Log in using your @provider.DisplayName account">Registre-se com @provider.DisplayName</button>
                                            }
                                        </p>
                                    </div>
                                </form>
                            }
                        }
                    </section>
                </div>
            </div>
        </div>
    </section>
</div>